### ISSUE TITLE
SJSU-1010, Display individual category

### ISSUE THREAD

**Issue by SandroSal** [Abcbadq/sjsu_shop#23]
Create a page that displays the result when clicked on a tile when shopping by category (Story: [SJSU-1009](https://github.com/Abcbadq/sjsu_shop/issues/22))

criteria:
- create new page that displays all products in a category (limit display to like 25 products or so and if there's more products, have multiple pages)

see [SJSU-1007](https://github.com/Abcbadq/sjsu_shop/issues/20), which also includes a display of search results. Maybe we can use one new page to display search results as well as category results.

**Comment by justinmmagadia** [comment]
https://github.com/justinmmagadia/CS151/blob/master/DisplayByCategory.html

**Comment by justinmmagadia** [comment]
https://github.com/Abcbadq/sjsu_shop/pull/45
